name: Build and Deploy React App to cPanel Repo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build React project
        run: npm run build

      - name: Push build output to deploy branch
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.CPANEL_REPO_TOKEN }}
        with:
          source-directory: dist
          destination-repository-username: MVA-Chronosphere
          destination-repository-name: MVA_NACL
          target-branch: deploy
          target-directory: dist
          user-name: github-actions
          user-email: github-actions@github.com
          commit-message: "Auto-update build"
